- hosts: localhost
  tasks:
    tasks:
      - import_tasks: tasks/vscode.yaml
        tags:
          - vscode
      - import_tasks: tasks/flatpak.yaml
        tags:
          - flatpak
      - import_tasks: tasks/docker.yaml
        tags:
          - docker
      - import_tasks: tasks/python.yaml
        tags:
          - python
