- name: Install Pyenv with pyenv-installer
  become_user: artud
  shell: curl https://pyenv.run | bash
  tags:
    - pyenv

- name: Add pyenv to PATH
  become_user: artud
  blockinfile:
    dest: "{{ ansible_env.HOME }}/.bash_profile"
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init -)"
    marker: "# {mark} ANSIBLE MANAGED BLOCK - pyenv"
    insertbefore: EOF
  tags:
    - pyenv
